name: DumprX on GitHub

on:
  workflow_dispatch:
    inputs:
      ROM_LINK:
        description: "Direct Link of ROM/Firmware"
        required: true

env:
  ROM_LINK: ${{ github.event.inputs.ROM_LINK }}
  GIT_ORG: ${{ secrets.GIT_ORG }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Checkouts
        uses: actions/checkout@v4
        
      - name: Dump
        run: |
          mkdir -p ~/job && cd ~/job
          git clone https://github.com/Van-Firmware-Dumps/DumprX.git DumprX
          cd DumprX
          sudo bash ./setup.sh || exit 1
          sudo apt install -y f2fs-tools neofetch
          echo "$GIT_TOKEN" > .github_token
          echo "$GIT_ORG" > .github_orgname
          echo "$TG_TOKEN" > .tg_token
          echo "$CHAT_ID" > .tg_chat
          pip3 install git+https://github.com/ananjaser1211/samloader.git > /dev/null 2>&1
          samloader -m SM-M156B -r INS -i 354773371234562 download -O . > /dev/null 2>&1
          ls -a && exit 0
          ./dumper.sh "${ROM_LINK}" || exit 1

          echo test, and deploy your project.
